spring.datasource.url=jdbc:postgresql://localhost:5432/assistant_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8080


security.token.secret=Bck-End#
security.token.issuer=backend-assistent
app.admin.name=Administrador Sistema
app.admin.email=admin@teste.com
app.admin.password=admin12345

app.storage.base-dir=${APP_STORAGE_BASE_DIR:../assistente_chatbot/pts_chatbot}
app.storage.pts-excel-path=${APP_STORAGE_PTS_EXCEL_PATH:${app.storage.base-dir}/data/PTS_Agriproducts_02.xlsx}
app.storage.it-dir=${APP_STORAGE_IT_DIR:${app.storage.base-dir}/docs/ITs}

spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=30MB
